# Site settings
title: SU2 | Multiphysics Simulation and Design Software
email: info@su2foundation.org
description: >
  Website for the SU2 Project

baseurl: "/" # the subpath of your site, e.g. /blog/
url: https://doc.qtser.xyz # the base hostname & protocol for your site
git_address: https://github.com/su2code/SU2.git
git_edit_address: https://github.com/su2code/su2code.github.io/blob/master

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: yeti

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-redirect-from


exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs_v7
    type: docs_v7
  values:
    layout: docs_v7
    sectionid: docs_v7
    seo:
      type: "WebPage"

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _tutorials
    type: tutorials
  values:
    layout: tutorials
    sectionid: tutorials
    seo:
      type: "WebPage"

- scope:
    path: _vandv
    type: vandv
  values:
    layout: vandv
    sectionid: vandv
    seo:
      type: "WebPage"
collections:
  docs:
    permalink: /:collection/:path/
    output: true
  docs_v7:
    permalink: /:collection/:path/
    output: true
  tutorials:
    permalink: /:collection/:path/
    output: true
  vandv:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true

# Google Analytics
google_analytics: UA-28187985-1

plugins:
  - jekyll-gist
